
DROP DATABASE IF EXISTS TAREFAS;
CREATE DATABASE TAREFAS;
USE TAREFAS;


DROP USER IF EXISTS 'tarefas'@'localhost';
CREATE USER 'tarefas'@'localhost' IDENTIFIED BY 'tarefa@123';


GRANT SELECT, INSERT, UPDATE, DELETE ON TAREFAS.* TO 'tarefas'@'localhost';
FLUSH PRIVILEGES;


CREATE TABLE TAREFAS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL UNIQUE,
    CUSTO DECIMAL(10,2),
    DATA_LIMITE DATE,
    ORDEM INT NOT NULL 
);
